---
  stages:
    - commit
    - linter

  git-history:
    stage: commit
    script:
      - >
        bash <(curl -s
        https://gitlab.com/yue-script/checks/raw/master/check_git_history.sh)

  lines-length:
    stage: commit
    script:
      - >
        bash <(curl -s
        https://gitlab.com/yue-script/checks/raw/master/check_lines_length.sh)
        80 README.md

  pylama:
    stage: linter
    image: vpgrp/linter:python
    script:
      - pylama mdc
  # EOF
